In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv("../dataset/Bank Customer Churn Prediction.csv")
# drop customer id
df = df.drop('customer_id', axis=1)
df.head()

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [54]:
# nella colonna gneder voglio sostituire Male con 0 e Female con 1
# non usare dummy, ma fare una sostituzione diretta
df['gender'] = df['gender'].replace({'Male': 0, 'Female': 1}) 
df.tail()

C:\Users\marco\AppData\Local\Temp\ipykernel_22708\2552816008.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace({'Male': 0, 'Female': 1})

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
9995,771,France,0,39,5,0.00,2,1,0,96270.64,0
9996,516,France,0,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,1,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,0,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,1,28,4,130142.79,1,1,0,38190.78,0

In [55]:
c = pd.get_dummies(df['country'],prefix='country')
# sostituisco True/False con 1/0
c = c.astype(int)

# rimuovo la colonna country originale
df = df.drop('country', axis=1)
# aggiungo le nuove colonne create con get_dummies
df = pd.concat([df, c], axis=1)
df.head()

,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,country_France,country_Germany,country_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,1,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,1,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,1,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,1,43,2,125510.82,1,1,1,79084.10,0,0,0,1

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   credit_score      10000 non-null  int64
 1   gender            10000 non-null  int64
 2   age               10000 non-null  int64
 3   tenure            10000 non-null  int64
 4   balance           10000 non-null  float64
 5   products_number   10000 non-null  int64
 6   credit_card       10000 non-null  int64
 7   active_member     10000 non-null  int64
 8   estimated_salary  10000 non-null  float64
 9   churn             10000 non-null  int64
 10  country_France    10000 non-null  int64
 11  country_Germany   10000 non-null  int64
 12  country_Spain     10000 non-null  int64
dtypes: float64(2), int64(11)
memory usage: 1015.8 KB

In [57]:
df

,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,country_France,country_Germany,country_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,1,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,1,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,1,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,1,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,0,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,1,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,0,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,1,28,4,130142.79,1,1,0,38190.78,0,1,0,0

In [58]:
X = df[df.columns.difference(['churn'])]
y = df['churn']

In [59]:
X

,active_member,age,balance,country_France,country_Germany,country_Spain,credit_card,credit_score,estimated_salary,gender,products_number,tenure
0,1,42,0.00,1,0,0,1,619,101348.88,1,1,2
1,1,41,83807.86,0,0,1,0,608,112542.58,1,1,1
2,0,42,159660.80,1,0,0,1,502,113931.57,1,3,8
3,0,39,0.00,1,0,0,0,699,93826.63,1,2,1
4,1,43,125510.82,0,0,1,1,850,79084.10,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,39,0.00,1,0,0,1,771,96270.64,0,2,5
9996,1,35,57369.61,1,0,0,1,516,101699.77,0,1,10
9997,1,36,0.00,1,0,0,0,709,42085.58,1,1,7
9998,0,42,75075.31,0,1,0,1,772,92888.52,0,2,3
9999,0,28,130142.79,1,0,0,1,792,38190.78,1,1,4

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [61]:
#X_train = df[df.columns.difference(['churn'])]
#y_train = df['churn']
#X_test = X_train
#y_test = y_train

In [65]:
# voglio creare un regressione logistica per predire churn a partire da tutte le altre variabili

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Accuracy: 0.718
Confusion Matrix:
 [[1156  451]
 [ 113  280]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.72      0.80      1607
           1       0.38      0.71      0.50       393

    accuracy                           0.72      2000
   macro avg       0.65      0.72      0.65      2000
weighted avg       0.81      0.72      0.74      2000

In [63]:
model.coef_

array([[-1.04460268,  5.08402117,  0.6314524 , -0.87274473, -0.09589308,
        -0.77997204, -0.02330163, -0.34535461,  0.04872286,  0.52810586,
        -0.31601384, -0.14469854]])

In [64]:
model.intercept_

array([-1.97034905])